// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/overcyn/matcha/pb/view/textinput/textinput.proto

/*
Package textinput is a generated protocol buffer package.

It is generated from these files:
	github.com/overcyn/matcha/pb/view/textinput/textinput.proto

It has these top-level messages:
	View
	Event
	FocusEvent
*/
package textinput

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import matcha_text "github.com/overcyn/matcha/pb/text"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type View struct {
	StyledText *matcha_text.StyledText `protobuf:"bytes,1,opt,name=styledText" json:"styledText,omitempty"`
	Focused    bool                    `protobuf:"varint,4,opt,name=focused" json:"focused,omitempty"`
	OnUpdate   int64                   `protobuf:"varint,2,opt,name=onUpdate" json:"onUpdate,omitempty"`
	OnFocus    int64                   `protobuf:"varint,3,opt,name=onFocus" json:"onFocus,omitempty"`
}

func (m *View) Reset()                    { *m = View{} }
func (m *View) String() string            { return proto.CompactTextString(m) }
func (*View) ProtoMessage()               {}
func (*View) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *View) GetStyledText() *matcha_text.StyledText {
	if m != nil {
		return m.StyledText
	}
	return nil
}

func (m *View) GetFocused() bool {
	if m != nil {
		return m.Focused
	}
	return false
}

func (m *View) GetOnUpdate() int64 {
	if m != nil {
		return m.OnUpdate
	}
	return 0
}

func (m *View) GetOnFocus() int64 {
	if m != nil {
		return m.OnFocus
	}
	return 0
}

type Event struct {
	StyledText *matcha_text.StyledText `protobuf:"bytes,1,opt,name=styledText" json:"styledText,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Event) GetStyledText() *matcha_text.StyledText {
	if m != nil {
		return m.StyledText
	}
	return nil
}

type FocusEvent struct {
	Focused bool `protobuf:"varint,1,opt,name=focused" json:"focused,omitempty"`
}

func (m *FocusEvent) Reset()                    { *m = FocusEvent{} }
func (m *FocusEvent) String() string            { return proto.CompactTextString(m) }
func (*FocusEvent) ProtoMessage()               {}
func (*FocusEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *FocusEvent) GetFocused() bool {
	if m != nil {
		return m.Focused
	}
	return false
}

func init() {
	proto.RegisterType((*View)(nil), "matcha.view.textinput.View")
	proto.RegisterType((*Event)(nil), "matcha.view.textinput.Event")
	proto.RegisterType((*FocusEvent)(nil), "matcha.view.textinput.FocusEvent")
}

func init() {
	proto.RegisterFile("github.com/overcyn/matcha/pb/view/textinput/textinput.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xb2, 0x4e, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0x2f, 0x4b, 0x2d, 0x4a, 0xae, 0xcc, 0xd3, 0xcf,
	0x4d, 0x2c, 0x49, 0xce, 0x48, 0xd4, 0x2f, 0x48, 0xd2, 0x2f, 0xcb, 0x4c, 0x2d, 0xd7, 0x2f, 0x49,
	0xad, 0x28, 0xc9, 0xcc, 0x2b, 0x28, 0x2d, 0x41, 0xb0, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85,
	0x44, 0x21, 0x2a, 0xf5, 0x40, 0xca, 0xf4, 0xe0, 0x92, 0x52, 0x3a, 0x78, 0xcd, 0x04, 0xa9, 0x03,
	0x13, 0x10, 0x43, 0x94, 0xfa, 0x19, 0xb9, 0x58, 0xc2, 0x32, 0x53, 0xcb, 0x85, 0xcc, 0xb9, 0xb8,
	0x8a, 0x4b, 0x2a, 0x73, 0x52, 0x53, 0x42, 0x52, 0x2b, 0x4a, 0x24, 0x18, 0x15, 0x18, 0x35, 0xb8,
	0x8d, 0xc4, 0xf5, 0xa0, 0x56, 0x80, 0x35, 0x04, 0xc3, 0xa5, 0x83, 0x90, 0x94, 0x0a, 0x49, 0x70,
	0xb1, 0xa7, 0xe5, 0x27, 0x97, 0x16, 0xa7, 0xa6, 0x48, 0xb0, 0x28, 0x30, 0x6a, 0x70, 0x04, 0xc1,
	0xb8, 0x42, 0x52, 0x5c, 0x1c, 0xf9, 0x79, 0xa1, 0x05, 0x29, 0x89, 0x25, 0xa9, 0x12, 0x4c, 0x0a,
	0x8c, 0x1a, 0xcc, 0x41, 0x70, 0x3e, 0x48, 0x57, 0x7e, 0x9e, 0x1b, 0x48, 0xa1, 0x04, 0x33, 0x58,
	0x0a, 0xc6, 0x55, 0x72, 0xe0, 0x62, 0x75, 0x2d, 0x4b, 0xcd, 0x2b, 0x21, 0xdb, 0x45, 0x4a, 0x6a,
	0x5c, 0x5c, 0x60, 0xa3, 0x20, 0xc6, 0x20, 0xb9, 0x8f, 0x11, 0xc5, 0x7d, 0x4e, 0xf2, 0x51, 0x9c,
	0xf0, 0x60, 0x5b, 0xc4, 0x24, 0xe8, 0x0b, 0x36, 0x19, 0x64, 0x82, 0x27, 0x48, 0x24, 0xc0, 0x29,
	0x89, 0x0d, 0x1c, 0x46, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x98, 0xbd, 0x93, 0xc8, 0xa7,
	0x01, 0x00, 0x00,
}
