// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: github.com/overcyn/mochi/pb/imageview.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "github.com/overcyn/mochi/pb/Imageview.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - MochiPBImageviewRoot

@implementation MochiPBImageviewRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - MochiPBImageviewRoot_FileDescriptor

static GPBFileDescriptor *MochiPBImageviewRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"imageview"
                                                 objcPrefix:@"MochiPB"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - Enum MochiPBResizeMode

GPBEnumDescriptor *MochiPBResizeMode_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Fit\000Fill\000Stretch\000Center\000";
    static const int32_t values[] = {
        MochiPBResizeMode_Fit,
        MochiPBResizeMode_Fill,
        MochiPBResizeMode_Stretch,
        MochiPBResizeMode_Center,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(MochiPBResizeMode)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:MochiPBResizeMode_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL MochiPBResizeMode_IsValidValue(int32_t value__) {
  switch (value__) {
    case MochiPBResizeMode_Fit:
    case MochiPBResizeMode_Fill:
    case MochiPBResizeMode_Stretch:
    case MochiPBResizeMode_Center:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - MochiPBImage

@implementation MochiPBImage

@dynamic width;
@dynamic height;
@dynamic data_p;

typedef struct MochiPBImage__storage_ {
  uint32_t _has_storage_[1];
  NSData *data_p;
  int64_t width;
  int64_t height;
} MochiPBImage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "width",
        .dataTypeSpecific.className = NULL,
        .number = MochiPBImage_FieldNumber_Width,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(MochiPBImage__storage_, width),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "height",
        .dataTypeSpecific.className = NULL,
        .number = MochiPBImage_FieldNumber_Height,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(MochiPBImage__storage_, height),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "data_p",
        .dataTypeSpecific.className = NULL,
        .number = MochiPBImage_FieldNumber_Data_p,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(MochiPBImage__storage_, data_p),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBytes,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[MochiPBImage class]
                                     rootClass:[MochiPBImageviewRoot class]
                                          file:MochiPBImageviewRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(MochiPBImage__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - MochiPBImageView

@implementation MochiPBImageView

@dynamic hasImage, image;
@dynamic resizeMode;

typedef struct MochiPBImageView__storage_ {
  uint32_t _has_storage_[1];
  MochiPBResizeMode resizeMode;
  MochiPBImage *image;
} MochiPBImageView__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "image",
        .dataTypeSpecific.className = GPBStringifySymbol(MochiPBImage),
        .number = MochiPBImageView_FieldNumber_Image,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(MochiPBImageView__storage_, image),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "resizeMode",
        .dataTypeSpecific.enumDescFunc = MochiPBResizeMode_EnumDescriptor,
        .number = MochiPBImageView_FieldNumber_ResizeMode,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(MochiPBImageView__storage_, resizeMode),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldHasEnumDescriptor),
        .dataType = GPBDataTypeEnum,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[MochiPBImageView class]
                                     rootClass:[MochiPBImageviewRoot class]
                                          file:MochiPBImageviewRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(MochiPBImageView__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\002\n\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t MochiPBImageView_ResizeMode_RawValue(MochiPBImageView *message) {
  GPBDescriptor *descriptor = [MochiPBImageView descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:MochiPBImageView_FieldNumber_ResizeMode];
  return GPBGetMessageInt32Field(message, field);
}

void SetMochiPBImageView_ResizeMode_RawValue(MochiPBImageView *message, int32_t value) {
  GPBDescriptor *descriptor = [MochiPBImageView descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:MochiPBImageView_FieldNumber_ResizeMode];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
