// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: github.com/overcyn/matcha/pb/layout.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "github.com/gomatcha/matcha/pb/Layout.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - MatchaPBLayoutRoot

@implementation MatchaPBLayoutRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - MatchaPBLayoutRoot_FileDescriptor

static GPBFileDescriptor *MatchaPBLayoutRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"layout"
                                                 objcPrefix:@"MatchaPB"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - MatchaPBPoint

@implementation MatchaPBPoint

@dynamic x;
@dynamic y;

typedef struct MatchaPBPoint__storage_ {
  uint32_t _has_storage_[1];
  double x;
  double y;
} MatchaPBPoint__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "x",
        .dataTypeSpecific.className = NULL,
        .number = MatchaPBPoint_FieldNumber_X,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(MatchaPBPoint__storage_, x),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeDouble,
      },
      {
        .name = "y",
        .dataTypeSpecific.className = NULL,
        .number = MatchaPBPoint_FieldNumber_Y,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(MatchaPBPoint__storage_, y),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeDouble,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[MatchaPBPoint class]
                                     rootClass:[MatchaPBLayoutRoot class]
                                          file:MatchaPBLayoutRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(MatchaPBPoint__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - MatchaPBRect

@implementation MatchaPBRect

@dynamic hasMin, min;
@dynamic hasMax, max;

typedef struct MatchaPBRect__storage_ {
  uint32_t _has_storage_[1];
  MatchaPBPoint *min;
  MatchaPBPoint *max;
} MatchaPBRect__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "min",
        .dataTypeSpecific.className = GPBStringifySymbol(MatchaPBPoint),
        .number = MatchaPBRect_FieldNumber_Min,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(MatchaPBRect__storage_, min),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "max",
        .dataTypeSpecific.className = GPBStringifySymbol(MatchaPBPoint),
        .number = MatchaPBRect_FieldNumber_Max,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(MatchaPBRect__storage_, max),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[MatchaPBRect class]
                                     rootClass:[MatchaPBLayoutRoot class]
                                          file:MatchaPBLayoutRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(MatchaPBRect__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - MatchaPBInsets

@implementation MatchaPBInsets

@dynamic top;
@dynamic left;
@dynamic bottom;
@dynamic right;

typedef struct MatchaPBInsets__storage_ {
  uint32_t _has_storage_[1];
  double top;
  double left;
  double bottom;
  double right;
} MatchaPBInsets__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "top",
        .dataTypeSpecific.className = NULL,
        .number = MatchaPBInsets_FieldNumber_Top,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(MatchaPBInsets__storage_, top),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeDouble,
      },
      {
        .name = "left",
        .dataTypeSpecific.className = NULL,
        .number = MatchaPBInsets_FieldNumber_Left,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(MatchaPBInsets__storage_, left),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeDouble,
      },
      {
        .name = "bottom",
        .dataTypeSpecific.className = NULL,
        .number = MatchaPBInsets_FieldNumber_Bottom,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(MatchaPBInsets__storage_, bottom),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeDouble,
      },
      {
        .name = "right",
        .dataTypeSpecific.className = NULL,
        .number = MatchaPBInsets_FieldNumber_Right,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(MatchaPBInsets__storage_, right),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeDouble,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[MatchaPBInsets class]
                                     rootClass:[MatchaPBLayoutRoot class]
                                          file:MatchaPBLayoutRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(MatchaPBInsets__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - MatchaPBGuide

@implementation MatchaPBGuide

@dynamic hasFrame, frame;
@dynamic hasInsets, insets;
@dynamic zIndex;

typedef struct MatchaPBGuide__storage_ {
  uint32_t _has_storage_[1];
  MatchaPBRect *frame;
  MatchaPBInsets *insets;
  int64_t zIndex;
} MatchaPBGuide__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "frame",
        .dataTypeSpecific.className = GPBStringifySymbol(MatchaPBRect),
        .number = MatchaPBGuide_FieldNumber_Frame,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(MatchaPBGuide__storage_, frame),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "insets",
        .dataTypeSpecific.className = GPBStringifySymbol(MatchaPBInsets),
        .number = MatchaPBGuide_FieldNumber_Insets,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(MatchaPBGuide__storage_, insets),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "zIndex",
        .dataTypeSpecific.className = NULL,
        .number = MatchaPBGuide_FieldNumber_ZIndex,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(MatchaPBGuide__storage_, zIndex),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[MatchaPBGuide class]
                                     rootClass:[MatchaPBLayoutRoot class]
                                          file:MatchaPBLayoutRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(MatchaPBGuide__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\003\006\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
