
// Objective-C API for talking to the following Go packages
//
//	github.com/overcyn/mochi/bridge
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Bridge_FRAMEWORK_H__
#define __Bridge_FRAMEWORK_H__

#include "Bridge.objc.h"
#include "Universe.objc.h"

#endif
