// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gomatcha.io/matcha/pb/view/segmentview/segmentview.proto

/*
Package segmentview is a generated protocol buffer package.

It is generated from these files:
	gomatcha.io/matcha/pb/view/segmentview/segmentview.proto

It has these top-level messages:
	View
	Event
*/
package segmentview

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type View struct {
	Value     int64    `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
	Title     []string `protobuf:"bytes,2,rep,name=title" json:"title,omitempty"`
	Momentary bool     `protobuf:"varint,3,opt,name=momentary" json:"momentary,omitempty"`
	Enabled   bool     `protobuf:"varint,4,opt,name=enabled" json:"enabled,omitempty"`
}

func (m *View) Reset()                    { *m = View{} }
func (m *View) String() string            { return proto.CompactTextString(m) }
func (*View) ProtoMessage()               {}
func (*View) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *View) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *View) GetTitle() []string {
	if m != nil {
		return m.Title
	}
	return nil
}

func (m *View) GetMomentary() bool {
	if m != nil {
		return m.Momentary
	}
	return false
}

func (m *View) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

type Event struct {
	Value int64 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Event) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*View)(nil), "segmentview.View")
	proto.RegisterType((*Event)(nil), "segmentview.Event")
}

func init() {
	proto.RegisterFile("gomatcha.io/matcha/pb/view/segmentview/segmentview.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xb2, 0x48, 0xcf, 0xcf, 0x4d,
	0x2c, 0x49, 0xce, 0x48, 0xd4, 0xcb, 0xcc, 0xd7, 0x87, 0xb0, 0xf4, 0x0b, 0x92, 0xf4, 0xcb, 0x32,
	0x53, 0xcb, 0xf5, 0x8b, 0x53, 0xd3, 0x73, 0x53, 0xf3, 0x4a, 0xd0, 0xd9, 0x7a, 0x05, 0x45, 0xf9,
	0x25, 0xf9, 0x42, 0xdc, 0x48, 0x42, 0x4a, 0x59, 0x5c, 0x2c, 0x61, 0x99, 0xa9, 0xe5, 0x42, 0x22,
	0x5c, 0xac, 0x65, 0x89, 0x39, 0xa5, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0x10, 0x0e,
	0x48, 0xb4, 0x24, 0xb3, 0x24, 0x27, 0x55, 0x82, 0x49, 0x81, 0x59, 0x83, 0x33, 0x08, 0xc2, 0x11,
	0x92, 0xe1, 0xe2, 0xcc, 0xcd, 0x07, 0x99, 0x90, 0x58, 0x54, 0x29, 0xc1, 0xac, 0xc0, 0xa8, 0xc1,
	0x11, 0x84, 0x10, 0x10, 0x92, 0xe0, 0x62, 0x4f, 0xcd, 0x4b, 0x4c, 0xca, 0x49, 0x4d, 0x91, 0x60,
	0x01, 0xcb, 0xc1, 0xb8, 0x4a, 0xb2, 0x5c, 0xac, 0xae, 0x65, 0xa9, 0x79, 0x25, 0xd8, 0x2d, 0x73,
	0x52, 0x8e, 0x42, 0x76, 0xd9, 0x22, 0x26, 0x61, 0x5f, 0xb0, 0xaf, 0x82, 0x21, 0x62, 0x20, 0x57,
	0x06, 0x24, 0x25, 0xb1, 0x81, 0xfd, 0x60, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xe8, 0xb4, 0xab,
	0xaa, 0xff, 0x00, 0x00, 0x00,
}
