// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gomatcha.io/matcha/pb/view/stacknav/stacknavigator.proto

/*
Package stacknav is a generated protocol buffer package.

It is generated from these files:
	gomatcha.io/matcha/pb/view/stacknav/stacknavigator.proto

It has these top-level messages:
	ChildView
	View
	Bar
	StackEvent
*/
package stacknav

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChildView struct {
	ViewId int64 `protobuf:"varint,1,opt,name=viewId" json:"viewId,omitempty"`
	BarId  int64 `protobuf:"varint,2,opt,name=barId" json:"barId,omitempty"`
}

func (m *ChildView) Reset()                    { *m = ChildView{} }
func (m *ChildView) String() string            { return proto.CompactTextString(m) }
func (*ChildView) ProtoMessage()               {}
func (*ChildView) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ChildView) GetViewId() int64 {
	if m != nil {
		return m.ViewId
	}
	return 0
}

func (m *ChildView) GetBarId() int64 {
	if m != nil {
		return m.BarId
	}
	return 0
}

type View struct {
	Children []*ChildView `protobuf:"bytes,1,rep,name=children" json:"children,omitempty"`
}

func (m *View) Reset()                    { *m = View{} }
func (m *View) String() string            { return proto.CompactTextString(m) }
func (*View) ProtoMessage()               {}
func (*View) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *View) GetChildren() []*ChildView {
	if m != nil {
		return m.Children
	}
	return nil
}

type Bar struct {
	Title                 string  `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	BackButtonHidden      bool    `protobuf:"varint,7,opt,name=backButtonHidden" json:"backButtonHidden,omitempty"`
	CustomBackButtonTitle bool    `protobuf:"varint,2,opt,name=customBackButtonTitle" json:"customBackButtonTitle,omitempty"`
	BackButtonTitle       string  `protobuf:"bytes,3,opt,name=backButtonTitle" json:"backButtonTitle,omitempty"`
	TitleViewId           int64   `protobuf:"varint,4,opt,name=titleViewId" json:"titleViewId,omitempty"`
	RightViewIds          []int64 `protobuf:"varint,5,rep,packed,name=rightViewIds" json:"rightViewIds,omitempty"`
	LeftViewIds           []int64 `protobuf:"varint,6,rep,packed,name=leftViewIds" json:"leftViewIds,omitempty"`
}

func (m *Bar) Reset()                    { *m = Bar{} }
func (m *Bar) String() string            { return proto.CompactTextString(m) }
func (*Bar) ProtoMessage()               {}
func (*Bar) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Bar) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Bar) GetBackButtonHidden() bool {
	if m != nil {
		return m.BackButtonHidden
	}
	return false
}

func (m *Bar) GetCustomBackButtonTitle() bool {
	if m != nil {
		return m.CustomBackButtonTitle
	}
	return false
}

func (m *Bar) GetBackButtonTitle() string {
	if m != nil {
		return m.BackButtonTitle
	}
	return ""
}

func (m *Bar) GetTitleViewId() int64 {
	if m != nil {
		return m.TitleViewId
	}
	return 0
}

func (m *Bar) GetRightViewIds() []int64 {
	if m != nil {
		return m.RightViewIds
	}
	return nil
}

func (m *Bar) GetLeftViewIds() []int64 {
	if m != nil {
		return m.LeftViewIds
	}
	return nil
}

type StackEvent struct {
	Id []int64 `protobuf:"varint,1,rep,packed,name=id" json:"id,omitempty"`
}

func (m *StackEvent) Reset()                    { *m = StackEvent{} }
func (m *StackEvent) String() string            { return proto.CompactTextString(m) }
func (*StackEvent) ProtoMessage()               {}
func (*StackEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *StackEvent) GetId() []int64 {
	if m != nil {
		return m.Id
	}
	return nil
}

func init() {
	proto.RegisterType((*ChildView)(nil), "matcha.view.stacknav.ChildView")
	proto.RegisterType((*View)(nil), "matcha.view.stacknav.View")
	proto.RegisterType((*Bar)(nil), "matcha.view.stacknav.Bar")
	proto.RegisterType((*StackEvent)(nil), "matcha.view.stacknav.StackEvent")
}

func init() {
	proto.RegisterFile("gomatcha.io/matcha/pb/view/stacknav/stacknavigator.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0x41, 0x4f, 0xf2, 0x40,
	0x14, 0x4c, 0xbb, 0xc0, 0x07, 0x8f, 0x2f, 0x6a, 0x56, 0x34, 0x3d, 0x98, 0xd8, 0xf4, 0xd4, 0x78,
	0x68, 0x13, 0xf5, 0xa0, 0xf1, 0x56, 0x62, 0x22, 0x07, 0x13, 0x53, 0x0c, 0x07, 0x6f, 0xdb, 0xee,
	0x0a, 0x1b, 0x60, 0x97, 0x2c, 0x0b, 0xfc, 0x0c, 0xff, 0x83, 0xbf, 0xd4, 0xec, 0x2b, 0x34, 0x88,
	0xdc, 0x76, 0xe6, 0xcd, 0xbc, 0x79, 0x99, 0x85, 0x87, 0xb1, 0x9e, 0x33, 0x5b, 0x4e, 0x58, 0x22,
	0x75, 0x5a, 0xbd, 0xd2, 0x45, 0x91, 0xae, 0xa5, 0xd8, 0xa4, 0x4b, 0xcb, 0xca, 0xa9, 0x62, 0xeb,
	0xfa, 0x21, 0xc7, 0xcc, 0x6a, 0x93, 0x2c, 0x8c, 0xb6, 0x9a, 0xf6, 0xb6, 0x3e, 0x27, 0x4d, 0x76,
	0x8a, 0xe8, 0x11, 0x3a, 0xfd, 0x89, 0x9c, 0xf1, 0x91, 0x14, 0x1b, 0x7a, 0x09, 0x2d, 0x37, 0x1d,
	0xf0, 0xc0, 0x0b, 0xbd, 0x98, 0xe4, 0x5b, 0x44, 0x7b, 0xd0, 0x2c, 0x98, 0x19, 0xf0, 0xc0, 0x47,
	0xba, 0x02, 0x51, 0x1f, 0x1a, 0xe8, 0x7a, 0x82, 0x76, 0xe9, 0x56, 0x18, 0xa1, 0x02, 0x2f, 0x24,
	0x71, 0xf7, 0xf6, 0x3a, 0x39, 0x96, 0x95, 0xd4, 0x41, 0x79, 0x6d, 0x88, 0xbe, 0x7c, 0x20, 0x19,
	0x33, 0x2e, 0xc2, 0x4a, 0x3b, 0x13, 0x98, 0xdc, 0xc9, 0x2b, 0x40, 0x6f, 0xe0, 0xac, 0x60, 0xe5,
	0x34, 0x5b, 0x59, 0xab, 0xd5, 0x8b, 0xe4, 0x5c, 0xa8, 0xe0, 0x5f, 0xe8, 0xc5, 0xed, 0xfc, 0x0f,
	0x4f, 0xef, 0xe1, 0xa2, 0x5c, 0x2d, 0xad, 0x9e, 0x67, 0xf5, 0xe4, 0x1d, 0x37, 0xfa, 0x68, 0x38,
	0x3e, 0xa4, 0x31, 0x9c, 0x16, 0x07, 0x7a, 0x82, 0x17, 0x1c, 0xd2, 0x34, 0x84, 0x2e, 0x1e, 0x35,
	0xaa, 0x1a, 0x6a, 0x60, 0x15, 0xfb, 0x14, 0x8d, 0xe0, 0xbf, 0x91, 0xe3, 0x89, 0xad, 0xe0, 0x32,
	0x68, 0x86, 0x24, 0x26, 0xf9, 0x2f, 0xce, 0x6d, 0x99, 0x89, 0xcf, 0x5a, 0xd2, 0x42, 0xc9, 0x3e,
	0x15, 0x5d, 0x01, 0x0c, 0x5d, 0x63, 0xcf, 0x6b, 0xa1, 0x2c, 0x3d, 0x01, 0x5f, 0x72, 0xac, 0x95,
	0xe4, 0xbe, 0xe4, 0x59, 0xf8, 0xd1, 0xde, 0xf5, 0xf9, 0xed, 0x9f, 0xbf, 0x62, 0xcd, 0x28, 0x1f,
	0x96, 0x46, 0x08, 0xf5, 0x96, 0x15, 0x2d, 0xfc, 0xee, 0xbb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x57, 0xb7, 0x58, 0x3a, 0x2a, 0x02, 0x00, 0x00,
}
