// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gomatcha.io/matcha/pb/view/view.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class GPBAny;
@class MatchaLayoutPBGuide;
@class MatchaPaintPBStyle;
@class MatchaViewPBNode;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MatchaViewPBViewRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MatchaViewPBViewRoot : GPBRootObject
@end

#pragma mark - MatchaViewPBNode

typedef GPB_ENUM(MatchaViewPBNode_FieldNumber) {
  MatchaViewPBNode_FieldNumber_Id_p = 1,
  MatchaViewPBNode_FieldNumber_BuildId = 2,
  MatchaViewPBNode_FieldNumber_LayoutId = 3,
  MatchaViewPBNode_FieldNumber_PaintId = 4,
  MatchaViewPBNode_FieldNumber_ChildrenArray = 5,
  MatchaViewPBNode_FieldNumber_LayoutGuide = 6,
  MatchaViewPBNode_FieldNumber_BridgeName = 7,
  MatchaViewPBNode_FieldNumber_BridgeValue = 8,
  MatchaViewPBNode_FieldNumber_PaintStyle = 9,
  MatchaViewPBNode_FieldNumber_Values = 10,
};

@interface MatchaViewPBNode : GPBMessage

@property(nonatomic, readwrite) int64_t id_p;

@property(nonatomic, readwrite) int64_t buildId;

@property(nonatomic, readwrite) int64_t layoutId;

@property(nonatomic, readwrite) int64_t paintId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *bridgeName;

@property(nonatomic, readwrite, strong, null_resettable) GPBAny *bridgeValue;
/** Test to see if @c bridgeValue has been set. */
@property(nonatomic, readwrite) BOOL hasBridgeValue;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, GPBAny*> *values;
/** The number of items in @c values without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger values_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MatchaViewPBNode*> *childrenArray;
/** The number of items in @c childrenArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger childrenArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) MatchaLayoutPBGuide *layoutGuide;
/** Test to see if @c layoutGuide has been set. */
@property(nonatomic, readwrite) BOOL hasLayoutGuide;

@property(nonatomic, readwrite, strong, null_resettable) MatchaPaintPBStyle *paintStyle;
/** Test to see if @c paintStyle has been set. */
@property(nonatomic, readwrite) BOOL hasPaintStyle;

@end

#pragma mark - MatchaViewPBRoot

typedef GPB_ENUM(MatchaViewPBRoot_FieldNumber) {
  MatchaViewPBRoot_FieldNumber_Node = 1,
};

@interface MatchaViewPBRoot : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) MatchaViewPBNode *node;
/** Test to see if @c node has been set. */
@property(nonatomic, readwrite) BOOL hasNode;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
