// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: imageview.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class MochiPBImage;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum MochiPBResizeMode

typedef GPB_ENUM(MochiPBResizeMode) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  MochiPBResizeMode_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  MochiPBResizeMode_Fit = 0,
  MochiPBResizeMode_Fill = 1,
  MochiPBResizeMode_Stretch = 2,
  MochiPBResizeMode_Center = 3,
};

GPBEnumDescriptor *MochiPBResizeMode_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL MochiPBResizeMode_IsValidValue(int32_t value);

#pragma mark - MochiPBImageviewRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MochiPBImageviewRoot : GPBRootObject
@end

#pragma mark - MochiPBImage

typedef GPB_ENUM(MochiPBImage_FieldNumber) {
  MochiPBImage_FieldNumber_Width = 1,
  MochiPBImage_FieldNumber_Height = 2,
  MochiPBImage_FieldNumber_Data_p = 3,
};

@interface MochiPBImage : GPBMessage

@property(nonatomic, readwrite) int64_t width;

@property(nonatomic, readwrite) int64_t height;

@property(nonatomic, readwrite, copy, null_resettable) NSData *data_p;

@end

#pragma mark - MochiPBImageView

typedef GPB_ENUM(MochiPBImageView_FieldNumber) {
  MochiPBImageView_FieldNumber_Image = 1,
  MochiPBImageView_FieldNumber_ResizeMode = 2,
};

@interface MochiPBImageView : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) MochiPBImage *image;
/** Test to see if @c image has been set. */
@property(nonatomic, readwrite) BOOL hasImage;

@property(nonatomic, readwrite) MochiPBResizeMode resizeMode;

@end

/**
 * Fetches the raw value of a @c MochiPBImageView's @c resizeMode property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t MochiPBImageView_ResizeMode_RawValue(MochiPBImageView *message);
/**
 * Sets the raw value of an @c MochiPBImageView's @c resizeMode property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetMochiPBImageView_ResizeMode_RawValue(MochiPBImageView *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
