// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: view.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Guide;
@class Node;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ViewRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ViewRoot : GPBRootObject
@end

#pragma mark - Node

typedef GPB_ENUM(Node_FieldNumber) {
  Node_FieldNumber_Id_p = 1,
  Node_FieldNumber_BuildId = 2,
  Node_FieldNumber_LayoutId = 3,
  Node_FieldNumber_PaintId = 4,
  Node_FieldNumber_ChildrenArray = 5,
  Node_FieldNumber_LayoutGuide = 6,
};

@interface Node : GPBMessage

@property(nonatomic, readwrite) int64_t id_p;

@property(nonatomic, readwrite) int64_t buildId;

@property(nonatomic, readwrite) int64_t layoutId;

@property(nonatomic, readwrite) int64_t paintId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Node*> *childrenArray;
/** The number of items in @c childrenArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger childrenArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) Guide *layoutGuide;
/** Test to see if @c layoutGuide has been set. */
@property(nonatomic, readwrite) BOOL hasLayoutGuide;

@end

#pragma mark - Root

typedef GPB_ENUM(Root_FieldNumber) {
  Root_FieldNumber_Node = 1,
};

@interface Root : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Node *node;
/** Test to see if @c node has been set. */
@property(nonatomic, readwrite) BOOL hasNode;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
