// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: github.com/overcyn/mochi/layout/encoding/layout.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Insets;
@class Point_Class;
@class Rect_Class;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - LayoutRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface LayoutRoot : GPBRootObject
@end

#pragma mark - Point_Class

typedef GPB_ENUM(Point_Class_FieldNumber) {
  Point_Class_FieldNumber_X = 1,
  Point_Class_FieldNumber_Y = 2,
};

@interface Point_Class : GPBMessage

@property(nonatomic, readwrite) double x;

@property(nonatomic, readwrite) double y;

@end

#pragma mark - Rect_Class

typedef GPB_ENUM(Rect_Class_FieldNumber) {
  Rect_Class_FieldNumber_Min = 1,
  Rect_Class_FieldNumber_Max = 2,
};

@interface Rect_Class : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Point_Class *min;
/** Test to see if @c min has been set. */
@property(nonatomic, readwrite) BOOL hasMin;

@property(nonatomic, readwrite, strong, null_resettable) Point_Class *max;
/** Test to see if @c max has been set. */
@property(nonatomic, readwrite) BOOL hasMax;

@end

#pragma mark - Insets

typedef GPB_ENUM(Insets_FieldNumber) {
  Insets_FieldNumber_Top = 1,
  Insets_FieldNumber_Left = 2,
  Insets_FieldNumber_Bottom = 3,
  Insets_FieldNumber_Right = 4,
};

@interface Insets : GPBMessage

@property(nonatomic, readwrite) double top;

@property(nonatomic, readwrite) double left;

@property(nonatomic, readwrite) double bottom;

@property(nonatomic, readwrite) double right;

@end

#pragma mark - Guide

typedef GPB_ENUM(Guide_FieldNumber) {
  Guide_FieldNumber_Frame = 1,
  Guide_FieldNumber_Insets = 2,
  Guide_FieldNumber_ZIndex = 3,
};

@interface Guide : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Rect_Class *frame;
/** Test to see if @c frame has been set. */
@property(nonatomic, readwrite) BOOL hasFrame;

@property(nonatomic, readwrite, strong, null_resettable) Insets *insets;
/** Test to see if @c insets has been set. */
@property(nonatomic, readwrite) BOOL hasInsets;

@property(nonatomic, readwrite) int64_t zIndex;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
