// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gomatcha.io/matcha/pb/layout/layout.proto

/*
Package layout is a generated protocol buffer package.

It is generated from these files:
	gomatcha.io/matcha/pb/layout/layout.proto

It has these top-level messages:
	Point
	Rect
	Insets
	Guide
*/
package layout

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Point struct {
	X float64 `protobuf:"fixed64,1,opt,name=x" json:"x,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=y" json:"y,omitempty"`
}

func (m *Point) Reset()                    { *m = Point{} }
func (m *Point) String() string            { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()               {}
func (*Point) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Point) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Point) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Rect struct {
	Min *Point `protobuf:"bytes,1,opt,name=min" json:"min,omitempty"`
	Max *Point `protobuf:"bytes,2,opt,name=max" json:"max,omitempty"`
}

func (m *Rect) Reset()                    { *m = Rect{} }
func (m *Rect) String() string            { return proto.CompactTextString(m) }
func (*Rect) ProtoMessage()               {}
func (*Rect) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Rect) GetMin() *Point {
	if m != nil {
		return m.Min
	}
	return nil
}

func (m *Rect) GetMax() *Point {
	if m != nil {
		return m.Max
	}
	return nil
}

type Insets struct {
	Top    float64 `protobuf:"fixed64,1,opt,name=top" json:"top,omitempty"`
	Left   float64 `protobuf:"fixed64,2,opt,name=left" json:"left,omitempty"`
	Bottom float64 `protobuf:"fixed64,3,opt,name=bottom" json:"bottom,omitempty"`
	Right  float64 `protobuf:"fixed64,4,opt,name=right" json:"right,omitempty"`
}

func (m *Insets) Reset()                    { *m = Insets{} }
func (m *Insets) String() string            { return proto.CompactTextString(m) }
func (*Insets) ProtoMessage()               {}
func (*Insets) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Insets) GetTop() float64 {
	if m != nil {
		return m.Top
	}
	return 0
}

func (m *Insets) GetLeft() float64 {
	if m != nil {
		return m.Left
	}
	return 0
}

func (m *Insets) GetBottom() float64 {
	if m != nil {
		return m.Bottom
	}
	return 0
}

func (m *Insets) GetRight() float64 {
	if m != nil {
		return m.Right
	}
	return 0
}

type Guide struct {
	Frame  *Rect   `protobuf:"bytes,1,opt,name=frame" json:"frame,omitempty"`
	Insets *Insets `protobuf:"bytes,2,opt,name=insets" json:"insets,omitempty"`
	ZIndex int64   `protobuf:"varint,3,opt,name=zIndex" json:"zIndex,omitempty"`
}

func (m *Guide) Reset()                    { *m = Guide{} }
func (m *Guide) String() string            { return proto.CompactTextString(m) }
func (*Guide) ProtoMessage()               {}
func (*Guide) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Guide) GetFrame() *Rect {
	if m != nil {
		return m.Frame
	}
	return nil
}

func (m *Guide) GetInsets() *Insets {
	if m != nil {
		return m.Insets
	}
	return nil
}

func (m *Guide) GetZIndex() int64 {
	if m != nil {
		return m.ZIndex
	}
	return 0
}

func init() {
	proto.RegisterType((*Point)(nil), "matcha.layout.Point")
	proto.RegisterType((*Rect)(nil), "matcha.layout.Rect")
	proto.RegisterType((*Insets)(nil), "matcha.layout.Insets")
	proto.RegisterType((*Guide)(nil), "matcha.layout.Guide")
}

func init() { proto.RegisterFile("gomatcha.io/matcha/pb/layout/layout.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x4a, 0xf3, 0x40,
	0x10, 0xc7, 0x49, 0x93, 0xec, 0x61, 0xbe, 0x4f, 0x91, 0xb1, 0x4a, 0xbc, 0x49, 0x04, 0xb1, 0x07,
	0x13, 0xd0, 0x37, 0xe8, 0x45, 0x0a, 0x0a, 0x65, 0x0f, 0x1e, 0xc4, 0xcb, 0xa6, 0xdd, 0xb6, 0x0b,
	0x4d, 0x36, 0xa4, 0x53, 0xd8, 0xf8, 0x38, 0x3e, 0xa9, 0xec, 0xec, 0x5e, 0x2c, 0x78, 0xda, 0xf9,
	0x0f, 0xbf, 0x99, 0xfd, 0x2d, 0x0b, 0xb3, 0xad, 0x6d, 0x15, 0xad, 0x76, 0xaa, 0x32, 0xb6, 0x0e,
	0x55, 0xdd, 0x37, 0xf5, 0x5e, 0x8d, 0xf6, 0x48, 0xf1, 0xa8, 0xfa, 0xc1, 0x92, 0xc5, 0xb3, 0x08,
	0x86, 0x66, 0x79, 0x07, 0xf9, 0xd2, 0x9a, 0x8e, 0xf0, 0x3f, 0x24, 0xae, 0x48, 0x6e, 0x93, 0x87,
	0x44, 0x26, 0xce, 0xa7, 0xb1, 0x98, 0x84, 0x34, 0x96, 0xef, 0x90, 0x49, 0xbd, 0x22, 0xbc, 0x87,
	0xb4, 0x35, 0x1d, 0x53, 0xff, 0x9e, 0xa6, 0xd5, 0xaf, 0x4d, 0x15, 0xaf, 0x91, 0x1e, 0x60, 0x4e,
	0x39, 0x9e, 0xff, 0x9b, 0x53, 0xae, 0xfc, 0x04, 0xb1, 0xe8, 0x0e, 0x9a, 0x0e, 0x78, 0x01, 0x29,
	0xd9, 0x3e, 0xde, 0xef, 0x4b, 0x44, 0xc8, 0xf6, 0x7a, 0x43, 0x51, 0x82, 0x6b, 0xbc, 0x06, 0xd1,
	0x58, 0x22, 0xdb, 0x16, 0x29, 0x77, 0x63, 0xc2, 0x29, 0xe4, 0x83, 0xd9, 0xee, 0xa8, 0xc8, 0xb8,
	0x1d, 0x42, 0x39, 0x42, 0xfe, 0x72, 0x34, 0x6b, 0x8d, 0x33, 0xc8, 0x37, 0x83, 0x6a, 0x75, 0x14,
	0xbf, 0x3c, 0x11, 0xf2, 0x4f, 0x93, 0x81, 0xc0, 0x47, 0x10, 0x86, 0x8d, 0xa2, 0xfc, 0xd5, 0x09,
	0x1b, 0x74, 0x65, 0x84, 0xbc, 0xd0, 0xd7, 0xa2, 0x5b, 0x6b, 0xc7, 0x42, 0xa9, 0x8c, 0x69, 0x7e,
	0xf3, 0x21, 0xc2, 0xc0, 0xf7, 0xe4, 0xfc, 0x8d, 0x17, 0xbc, 0x72, 0x5c, 0xce, 0x1b, 0xc1, 0xdf,
	0xf0, 0xfc, 0x13, 0x00, 0x00, 0xff, 0xff, 0x27, 0x81, 0xa1, 0xfc, 0xb3, 0x01, 0x00, 0x00,
}
