// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: github.com/overcyn/matcha/pb/imageview.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "github.com/overcyn/matcha/pb/Imageview.pbobjc.h"
 #import "github.com/overcyn/matcha/pb/Color.pbobjc.h"
 #import "github.com/overcyn/matcha/pb/env/Resource.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - MatchaPBImageviewRoot

@implementation MatchaPBImageviewRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - MatchaPBImageviewRoot_FileDescriptor

static GPBFileDescriptor *MatchaPBImageviewRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"imageview"
                                                 objcPrefix:@"MatchaPB"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - Enum MatchaPBResizeMode

GPBEnumDescriptor *MatchaPBResizeMode_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Fit\000Fill\000Stretch\000Center\000";
    static const int32_t values[] = {
        MatchaPBResizeMode_Fit,
        MatchaPBResizeMode_Fill,
        MatchaPBResizeMode_Stretch,
        MatchaPBResizeMode_Center,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(MatchaPBResizeMode)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:MatchaPBResizeMode_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL MatchaPBResizeMode_IsValidValue(int32_t value__) {
  switch (value__) {
    case MatchaPBResizeMode_Fit:
    case MatchaPBResizeMode_Fill:
    case MatchaPBResizeMode_Stretch:
    case MatchaPBResizeMode_Center:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - MatchaPBImage

@implementation MatchaPBImage

@dynamic width;
@dynamic height;
@dynamic stride;
@dynamic data_p;

typedef struct MatchaPBImage__storage_ {
  uint32_t _has_storage_[1];
  NSData *data_p;
  int64_t width;
  int64_t height;
  int64_t stride;
} MatchaPBImage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "width",
        .dataTypeSpecific.className = NULL,
        .number = MatchaPBImage_FieldNumber_Width,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(MatchaPBImage__storage_, width),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "height",
        .dataTypeSpecific.className = NULL,
        .number = MatchaPBImage_FieldNumber_Height,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(MatchaPBImage__storage_, height),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "data_p",
        .dataTypeSpecific.className = NULL,
        .number = MatchaPBImage_FieldNumber_Data_p,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(MatchaPBImage__storage_, data_p),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBytes,
      },
      {
        .name = "stride",
        .dataTypeSpecific.className = NULL,
        .number = MatchaPBImage_FieldNumber_Stride,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(MatchaPBImage__storage_, stride),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[MatchaPBImage class]
                                     rootClass:[MatchaPBImageviewRoot class]
                                          file:MatchaPBImageviewRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(MatchaPBImage__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - MatchaPBImageView

@implementation MatchaPBImageView

@dynamic hasImage, image;
@dynamic hasResource, resource;
@dynamic resizeMode;
@dynamic hasTint, tint;

typedef struct MatchaPBImageView__storage_ {
  uint32_t _has_storage_[1];
  MatchaPBResizeMode resizeMode;
  MatchaPBImage *image;
  MatchaPBColor *tint;
  MatchaPBEnvResource *resource;
} MatchaPBImageView__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "image",
        .dataTypeSpecific.className = GPBStringifySymbol(MatchaPBImage),
        .number = MatchaPBImageView_FieldNumber_Image,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(MatchaPBImageView__storage_, image),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "resizeMode",
        .dataTypeSpecific.enumDescFunc = MatchaPBResizeMode_EnumDescriptor,
        .number = MatchaPBImageView_FieldNumber_ResizeMode,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(MatchaPBImageView__storage_, resizeMode),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldHasEnumDescriptor),
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "tint",
        .dataTypeSpecific.className = GPBStringifySymbol(MatchaPBColor),
        .number = MatchaPBImageView_FieldNumber_Tint,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(MatchaPBImageView__storage_, tint),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "resource",
        .dataTypeSpecific.className = GPBStringifySymbol(MatchaPBEnvResource),
        .number = MatchaPBImageView_FieldNumber_Resource,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(MatchaPBImageView__storage_, resource),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[MatchaPBImageView class]
                                     rootClass:[MatchaPBImageviewRoot class]
                                          file:MatchaPBImageviewRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(MatchaPBImageView__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\002\n\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t MatchaPBImageView_ResizeMode_RawValue(MatchaPBImageView *message) {
  GPBDescriptor *descriptor = [MatchaPBImageView descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:MatchaPBImageView_FieldNumber_ResizeMode];
  return GPBGetMessageInt32Field(message, field);
}

void SetMatchaPBImageView_ResizeMode_RawValue(MatchaPBImageView *message, int32_t value) {
  GPBDescriptor *descriptor = [MatchaPBImageView descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:MatchaPBImageView_FieldNumber_ResizeMode];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
