// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: github.com/overcyn/matcha/pb/paint.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class MatchaPBColor;
@class MatchaPBPoint;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MatchaPBPaintRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MatchaPBPaintRoot : GPBRootObject
@end

#pragma mark - MatchaPBPaintStyle

typedef GPB_ENUM(MatchaPBPaintStyle_FieldNumber) {
  MatchaPBPaintStyle_FieldNumber_Transparency = 1,
  MatchaPBPaintStyle_FieldNumber_BackgroundColor = 2,
  MatchaPBPaintStyle_FieldNumber_BorderColor = 3,
  MatchaPBPaintStyle_FieldNumber_BorderWidth = 4,
  MatchaPBPaintStyle_FieldNumber_CornerRadius = 5,
  MatchaPBPaintStyle_FieldNumber_ShadowRadius = 7,
  MatchaPBPaintStyle_FieldNumber_ShadowOffset = 8,
  MatchaPBPaintStyle_FieldNumber_ShadowColor = 9,
};

@interface MatchaPBPaintStyle : GPBMessage

@property(nonatomic, readwrite) double transparency;

@property(nonatomic, readwrite, strong, null_resettable) MatchaPBColor *backgroundColor;
/** Test to see if @c backgroundColor has been set. */
@property(nonatomic, readwrite) BOOL hasBackgroundColor;

@property(nonatomic, readwrite, strong, null_resettable) MatchaPBColor *borderColor;
/** Test to see if @c borderColor has been set. */
@property(nonatomic, readwrite) BOOL hasBorderColor;

@property(nonatomic, readwrite) double borderWidth;

@property(nonatomic, readwrite) double cornerRadius;

@property(nonatomic, readwrite) double shadowRadius;

@property(nonatomic, readwrite, strong, null_resettable) MatchaPBPoint *shadowOffset;
/** Test to see if @c shadowOffset has been set. */
@property(nonatomic, readwrite) BOOL hasShadowOffset;

@property(nonatomic, readwrite, strong, null_resettable) MatchaPBColor *shadowColor;
/** Test to see if @c shadowColor has been set. */
@property(nonatomic, readwrite) BOOL hasShadowColor;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
