// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: github.com/overcyn/matcha/pb/view.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/Any.pbobjc.h>
#else
 #import "google/protobuf/Any.pbobjc.h"
#endif

 #import "github.com/overcyn/matcha/pb/View.pbobjc.h"
 #import "github.com/overcyn/matcha/pb/Layout.pbobjc.h"
 #import "github.com/overcyn/matcha/pb/Paint.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - MatchaPBViewRoot

@implementation MatchaPBViewRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - MatchaPBViewRoot_FileDescriptor

static GPBFileDescriptor *MatchaPBViewRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"matcha"
                                                 objcPrefix:@"MatchaPB"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - MatchaPBNode

@implementation MatchaPBNode

@dynamic id_p;
@dynamic buildId;
@dynamic layoutId;
@dynamic paintId;
@dynamic bridgeName;
@dynamic hasBridgeValue, bridgeValue;
@dynamic values, values_Count;
@dynamic childrenArray, childrenArray_Count;
@dynamic hasLayoutGuide, layoutGuide;
@dynamic hasPaintStyle, paintStyle;

typedef struct MatchaPBNode__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *childrenArray;
  MatchaPBGuide *layoutGuide;
  NSString *bridgeName;
  GPBAny *bridgeValue;
  MatchaPBPaintStyle *paintStyle;
  NSMutableDictionary *values;
  int64_t id_p;
  int64_t buildId;
  int64_t layoutId;
  int64_t paintId;
} MatchaPBNode__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "id_p",
        .dataTypeSpecific.className = NULL,
        .number = MatchaPBNode_FieldNumber_Id_p,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(MatchaPBNode__storage_, id_p),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "buildId",
        .dataTypeSpecific.className = NULL,
        .number = MatchaPBNode_FieldNumber_BuildId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(MatchaPBNode__storage_, buildId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "layoutId",
        .dataTypeSpecific.className = NULL,
        .number = MatchaPBNode_FieldNumber_LayoutId,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(MatchaPBNode__storage_, layoutId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "paintId",
        .dataTypeSpecific.className = NULL,
        .number = MatchaPBNode_FieldNumber_PaintId,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(MatchaPBNode__storage_, paintId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "childrenArray",
        .dataTypeSpecific.className = GPBStringifySymbol(MatchaPBNode),
        .number = MatchaPBNode_FieldNumber_ChildrenArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(MatchaPBNode__storage_, childrenArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "layoutGuide",
        .dataTypeSpecific.className = GPBStringifySymbol(MatchaPBGuide),
        .number = MatchaPBNode_FieldNumber_LayoutGuide,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(MatchaPBNode__storage_, layoutGuide),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "bridgeName",
        .dataTypeSpecific.className = NULL,
        .number = MatchaPBNode_FieldNumber_BridgeName,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(MatchaPBNode__storage_, bridgeName),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "bridgeValue",
        .dataTypeSpecific.className = GPBStringifySymbol(GPBAny),
        .number = MatchaPBNode_FieldNumber_BridgeValue,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(MatchaPBNode__storage_, bridgeValue),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "paintStyle",
        .dataTypeSpecific.className = GPBStringifySymbol(MatchaPBPaintStyle),
        .number = MatchaPBNode_FieldNumber_PaintStyle,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(MatchaPBNode__storage_, paintStyle),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "values",
        .dataTypeSpecific.className = GPBStringifySymbol(GPBAny),
        .number = MatchaPBNode_FieldNumber_Values,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(MatchaPBNode__storage_, values),
        .flags = GPBFieldMapKeyString,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[MatchaPBNode class]
                                     rootClass:[MatchaPBViewRoot class]
                                          file:MatchaPBViewRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(MatchaPBNode__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\007\002\007\000\003\010\000\004\007\000\006\013\000\007\n\000\010\013\000\t\n\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - MatchaPBRoot

@implementation MatchaPBRoot

@dynamic hasNode, node;

typedef struct MatchaPBRoot__storage_ {
  uint32_t _has_storage_[1];
  MatchaPBNode *node;
} MatchaPBRoot__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "node",
        .dataTypeSpecific.className = GPBStringifySymbol(MatchaPBNode),
        .number = MatchaPBRoot_FieldNumber_Node,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(MatchaPBRoot__storage_, node),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[MatchaPBRoot class]
                                     rootClass:[MatchaPBViewRoot class]
                                          file:MatchaPBViewRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(MatchaPBRoot__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
