// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/overcyn/mochi/pb/imageview.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	github.com/overcyn/mochi/pb/imageview.proto
	github.com/overcyn/mochi/pb/layout.proto
	github.com/overcyn/mochi/pb/paint.proto
	github.com/overcyn/mochi/pb/scrollview.proto
	github.com/overcyn/mochi/pb/text.proto
	github.com/overcyn/mochi/pb/touch.proto
	github.com/overcyn/mochi/pb/view.proto

It has these top-level messages:
	Image
	ImageView
	Point
	Rect
	Insets
	Guide
	PaintStyle
	ScrollView
	SizeFunc
	Text
	Font
	Color
	TextStyle
	Recognizer
	RecognizerList
	TapRecognizer
	TapEvent
	PressRecognizer
	PressEvent
	PanRecognizer
	Node
	Root
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ResizeMode int32

const (
	ResizeMode_FIT     ResizeMode = 0
	ResizeMode_FILL    ResizeMode = 1
	ResizeMode_STRETCH ResizeMode = 2
	ResizeMode_CENTER  ResizeMode = 3
)

var ResizeMode_name = map[int32]string{
	0: "FIT",
	1: "FILL",
	2: "STRETCH",
	3: "CENTER",
}
var ResizeMode_value = map[string]int32{
	"FIT":     0,
	"FILL":    1,
	"STRETCH": 2,
	"CENTER":  3,
}

func (x ResizeMode) String() string {
	return proto.EnumName(ResizeMode_name, int32(x))
}
func (ResizeMode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Image struct {
	Width  int64  `protobuf:"varint,1,opt,name=width" json:"width,omitempty"`
	Height int64  `protobuf:"varint,2,opt,name=height" json:"height,omitempty"`
	Stride int64  `protobuf:"varint,4,opt,name=stride" json:"stride,omitempty"`
	Data   []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *Image) Reset()                    { *m = Image{} }
func (m *Image) String() string            { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()               {}
func (*Image) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Image) GetWidth() int64 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Image) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Image) GetStride() int64 {
	if m != nil {
		return m.Stride
	}
	return 0
}

func (m *Image) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ImageView struct {
	Image      *Image     `protobuf:"bytes,1,opt,name=image" json:"image,omitempty"`
	ResizeMode ResizeMode `protobuf:"varint,2,opt,name=resizeMode,enum=imageview.ResizeMode" json:"resizeMode,omitempty"`
}

func (m *ImageView) Reset()                    { *m = ImageView{} }
func (m *ImageView) String() string            { return proto.CompactTextString(m) }
func (*ImageView) ProtoMessage()               {}
func (*ImageView) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ImageView) GetImage() *Image {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *ImageView) GetResizeMode() ResizeMode {
	if m != nil {
		return m.ResizeMode
	}
	return ResizeMode_FIT
}

func init() {
	proto.RegisterType((*Image)(nil), "imageview.Image")
	proto.RegisterType((*ImageView)(nil), "imageview.ImageView")
	proto.RegisterEnum("imageview.ResizeMode", ResizeMode_name, ResizeMode_value)
}

func init() { proto.RegisterFile("github.com/overcyn/mochi/pb/imageview.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xcd, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0xcd, 0xbf, 0xbd, 0x95, 0x12, 0x2e, 0x2a, 0x59, 0x96, 0x2e, 0xa4, 0x28, 0x24, 0x50,
	0x11, 0x5c, 0xb7, 0xa4, 0x18, 0x68, 0x45, 0xc6, 0xe0, 0xc2, 0x5d, 0x7e, 0x86, 0xcc, 0x15, 0xe2,
	0x84, 0x74, 0x6c, 0xd0, 0xc7, 0xf1, 0x49, 0x25, 0x13, 0x69, 0xbb, 0x9b, 0xf3, 0x9d, 0x03, 0xdf,
	0x70, 0xe1, 0xae, 0x22, 0x25, 0xbe, 0xf2, 0xb0, 0x90, 0x75, 0x24, 0xf7, 0xbc, 0x2d, 0xbe, 0x3f,
	0xa3, 0x5a, 0x16, 0x82, 0xa2, 0x26, 0x8f, 0xa8, 0xce, 0x2a, 0xbe, 0x27, 0xde, 0x85, 0x4d, 0x2b,
	0x95, 0xc4, 0xd1, 0x01, 0xcc, 0x32, 0x70, 0x92, 0x3e, 0xe0, 0x25, 0x38, 0x1d, 0x95, 0x4a, 0x04,
	0xc6, 0xd4, 0x98, 0x5b, 0x6c, 0x08, 0x78, 0x0d, 0xae, 0xe0, 0x54, 0x09, 0x15, 0x98, 0x1a, 0xff,
	0xa7, 0x9e, 0xef, 0x54, 0x4b, 0x25, 0x0f, 0xec, 0x81, 0x0f, 0x09, 0x11, 0xec, 0x32, 0x53, 0x59,
	0x60, 0x4d, 0x8d, 0xf9, 0x05, 0xd3, 0xef, 0xd9, 0x07, 0x8c, 0xb4, 0xe2, 0x8d, 0x78, 0x87, 0x37,
	0xe0, 0x68, 0xb9, 0xd6, 0x8c, 0x17, 0x7e, 0x78, 0xfc, 0x9b, 0x1e, 0xb1, 0xa1, 0xc6, 0x07, 0x80,
	0x96, 0xef, 0xe8, 0x87, 0x6f, 0x65, 0xc9, 0xb5, 0x7c, 0xb2, 0xb8, 0x3a, 0x19, 0xb3, 0x43, 0xc9,
	0x4e, 0x86, 0xb7, 0x8f, 0x00, 0xc7, 0x06, 0x3d, 0xb0, 0xd6, 0x49, 0xea, 0x9f, 0xe1, 0x39, 0xd8,
	0xeb, 0x64, 0xb3, 0xf1, 0x0d, 0x1c, 0x83, 0xf7, 0x9a, 0xb2, 0x38, 0x5d, 0x3d, 0xf9, 0x26, 0x02,
	0xb8, 0xab, 0xf8, 0x39, 0x8d, 0x99, 0x6f, 0x2d, 0x27, 0xef, 0x66, 0x93, 0xff, 0x9a, 0xde, 0xb6,
	0x3f, 0xda, 0xcb, 0x32, 0x77, 0xf5, 0xa9, 0xee, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x44, 0xc7,
	0x5b, 0xf7, 0x59, 0x01, 0x00, 0x00,
}
