// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/overcyn/mochi/pb/text.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type TextAlignment int32

const (
	TextAlignment_TEXT_ALIGNMENT_LEFT      TextAlignment = 0
	TextAlignment_TEXT_ALIGNMENT_RIGHT     TextAlignment = 1
	TextAlignment_TEXT_ALIGNMENT_CENTER    TextAlignment = 2
	TextAlignment_TEXT_ALIGNMENT_JUSTIFIED TextAlignment = 3
)

var TextAlignment_name = map[int32]string{
	0: "TEXT_ALIGNMENT_LEFT",
	1: "TEXT_ALIGNMENT_RIGHT",
	2: "TEXT_ALIGNMENT_CENTER",
	3: "TEXT_ALIGNMENT_JUSTIFIED",
}
var TextAlignment_value = map[string]int32{
	"TEXT_ALIGNMENT_LEFT":      0,
	"TEXT_ALIGNMENT_RIGHT":     1,
	"TEXT_ALIGNMENT_CENTER":    2,
	"TEXT_ALIGNMENT_JUSTIFIED": 3,
}

func (x TextAlignment) String() string {
	return proto.EnumName(TextAlignment_name, int32(x))
}
func (TextAlignment) EnumDescriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

type StrikethroughStyle int32

const (
	StrikethroughStyle_STRIKETHROUGH_STYLE_NONE   StrikethroughStyle = 0
	StrikethroughStyle_STRIKETHROUGH_STYLE_SINGLE StrikethroughStyle = 1
	StrikethroughStyle_STRIKETHROUGH_STYLE_DOUBLE StrikethroughStyle = 2
	StrikethroughStyle_STRIKETHROUGH_STYLE_THICK  StrikethroughStyle = 3
	StrikethroughStyle_STRIKETHROUGH_STYLE_DOTTED StrikethroughStyle = 4
	StrikethroughStyle_STRIKETHROUGH_STYLE_DASHED StrikethroughStyle = 5
)

var StrikethroughStyle_name = map[int32]string{
	0: "STRIKETHROUGH_STYLE_NONE",
	1: "STRIKETHROUGH_STYLE_SINGLE",
	2: "STRIKETHROUGH_STYLE_DOUBLE",
	3: "STRIKETHROUGH_STYLE_THICK",
	4: "STRIKETHROUGH_STYLE_DOTTED",
	5: "STRIKETHROUGH_STYLE_DASHED",
}
var StrikethroughStyle_value = map[string]int32{
	"STRIKETHROUGH_STYLE_NONE":   0,
	"STRIKETHROUGH_STYLE_SINGLE": 1,
	"STRIKETHROUGH_STYLE_DOUBLE": 2,
	"STRIKETHROUGH_STYLE_THICK":  3,
	"STRIKETHROUGH_STYLE_DOTTED": 4,
	"STRIKETHROUGH_STYLE_DASHED": 5,
}

func (x StrikethroughStyle) String() string {
	return proto.EnumName(StrikethroughStyle_name, int32(x))
}
func (StrikethroughStyle) EnumDescriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

type UnderlineStyle int32

const (
	UnderlineStyle_UNDRELINE_STYLE_NONE   UnderlineStyle = 0
	UnderlineStyle_UNDRELINE_STYLE_SINGLE UnderlineStyle = 1
	UnderlineStyle_UNDRELINE_STYLE_DOUBLE UnderlineStyle = 2
	UnderlineStyle_UNDRELINE_STYLE_THICK  UnderlineStyle = 3
	UnderlineStyle_UNDRELINE_STYLE_DOTTED UnderlineStyle = 4
	UnderlineStyle_UNDRELINE_STYLE_DASHED UnderlineStyle = 5
)

var UnderlineStyle_name = map[int32]string{
	0: "UNDRELINE_STYLE_NONE",
	1: "UNDRELINE_STYLE_SINGLE",
	2: "UNDRELINE_STYLE_DOUBLE",
	3: "UNDRELINE_STYLE_THICK",
	4: "UNDRELINE_STYLE_DOTTED",
	5: "UNDRELINE_STYLE_DASHED",
}
var UnderlineStyle_value = map[string]int32{
	"UNDRELINE_STYLE_NONE":   0,
	"UNDRELINE_STYLE_SINGLE": 1,
	"UNDRELINE_STYLE_DOUBLE": 2,
	"UNDRELINE_STYLE_THICK":  3,
	"UNDRELINE_STYLE_DOTTED": 4,
	"UNDRELINE_STYLE_DASHED": 5,
}

func (x UnderlineStyle) String() string {
	return proto.EnumName(UnderlineStyle_name, int32(x))
}
func (UnderlineStyle) EnumDescriptor() ([]byte, []int) { return fileDescriptor4, []int{2} }

type TextWrap int32

const (
	TextWrap_TEXT_WRAP_NONE      TextWrap = 0
	TextWrap_TEXT_WRAP_WORD      TextWrap = 1
	TextWrap_TEXT_WRAP_CHARACTER TextWrap = 2
)

var TextWrap_name = map[int32]string{
	0: "TEXT_WRAP_NONE",
	1: "TEXT_WRAP_WORD",
	2: "TEXT_WRAP_CHARACTER",
}
var TextWrap_value = map[string]int32{
	"TEXT_WRAP_NONE":      0,
	"TEXT_WRAP_WORD":      1,
	"TEXT_WRAP_CHARACTER": 2,
}

func (x TextWrap) String() string {
	return proto.EnumName(TextWrap_name, int32(x))
}
func (TextWrap) EnumDescriptor() ([]byte, []int) { return fileDescriptor4, []int{3} }

type Truncation int32

const (
	Truncation_TRUNCATION_NONE   Truncation = 0
	Truncation_TRUNCATION_START  Truncation = 1
	Truncation_TRUNCATION_MIDDLE Truncation = 2
	Truncation_TRUNCATION_END    Truncation = 3
)

var Truncation_name = map[int32]string{
	0: "TRUNCATION_NONE",
	1: "TRUNCATION_START",
	2: "TRUNCATION_MIDDLE",
	3: "TRUNCATION_END",
}
var Truncation_value = map[string]int32{
	"TRUNCATION_NONE":   0,
	"TRUNCATION_START":  1,
	"TRUNCATION_MIDDLE": 2,
	"TRUNCATION_END":    3,
}

func (x Truncation) String() string {
	return proto.EnumName(Truncation_name, int32(x))
}
func (Truncation) EnumDescriptor() ([]byte, []int) { return fileDescriptor4, []int{4} }

type SizeFunc struct {
	Text    *Text  `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	MinSize *Point `protobuf:"bytes,2,opt,name=minSize" json:"minSize,omitempty"`
	MaxSize *Point `protobuf:"bytes,3,opt,name=maxSize" json:"maxSize,omitempty"`
}

func (m *SizeFunc) Reset()                    { *m = SizeFunc{} }
func (m *SizeFunc) String() string            { return proto.CompactTextString(m) }
func (*SizeFunc) ProtoMessage()               {}
func (*SizeFunc) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *SizeFunc) GetText() *Text {
	if m != nil {
		return m.Text
	}
	return nil
}

func (m *SizeFunc) GetMinSize() *Point {
	if m != nil {
		return m.MinSize
	}
	return nil
}

func (m *SizeFunc) GetMaxSize() *Point {
	if m != nil {
		return m.MaxSize
	}
	return nil
}

type Text struct {
	Style *TextStyle `protobuf:"bytes,1,opt,name=style" json:"style,omitempty"`
	Text  string     `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
}

func (m *Text) Reset()                    { *m = Text{} }
func (m *Text) String() string            { return proto.CompactTextString(m) }
func (*Text) ProtoMessage()               {}
func (*Text) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *Text) GetStyle() *TextStyle {
	if m != nil {
		return m.Style
	}
	return nil
}

func (m *Text) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type Font struct {
	Family string  `protobuf:"bytes,1,opt,name=family" json:"family,omitempty"`
	Face   string  `protobuf:"bytes,2,opt,name=face" json:"face,omitempty"`
	Size   float64 `protobuf:"fixed64,3,opt,name=size" json:"size,omitempty"`
}

func (m *Font) Reset()                    { *m = Font{} }
func (m *Font) String() string            { return proto.CompactTextString(m) }
func (*Font) ProtoMessage()               {}
func (*Font) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{2} }

func (m *Font) GetFamily() string {
	if m != nil {
		return m.Family
	}
	return ""
}

func (m *Font) GetFace() string {
	if m != nil {
		return m.Face
	}
	return ""
}

func (m *Font) GetSize() float64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type Color struct {
	Red   uint32 `protobuf:"varint,1,opt,name=red" json:"red,omitempty"`
	Blue  uint32 `protobuf:"varint,2,opt,name=blue" json:"blue,omitempty"`
	Green uint32 `protobuf:"varint,3,opt,name=green" json:"green,omitempty"`
	Alpha uint32 `protobuf:"varint,4,opt,name=alpha" json:"alpha,omitempty"`
}

func (m *Color) Reset()                    { *m = Color{} }
func (m *Color) String() string            { return proto.CompactTextString(m) }
func (*Color) ProtoMessage()               {}
func (*Color) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{3} }

func (m *Color) GetRed() uint32 {
	if m != nil {
		return m.Red
	}
	return 0
}

func (m *Color) GetBlue() uint32 {
	if m != nil {
		return m.Blue
	}
	return 0
}

func (m *Color) GetGreen() uint32 {
	if m != nil {
		return m.Green
	}
	return 0
}

func (m *Color) GetAlpha() uint32 {
	if m != nil {
		return m.Alpha
	}
	return 0
}

type TextStyle struct {
	TextAlignment      TextAlignment      `protobuf:"varint,2,opt,name=textAlignment,enum=text.TextAlignment" json:"textAlignment,omitempty"`
	StrikethroughStyle StrikethroughStyle `protobuf:"varint,4,opt,name=strikethroughStyle,enum=text.StrikethroughStyle" json:"strikethroughStyle,omitempty"`
	StrikethroughColor *Color             `protobuf:"bytes,6,opt,name=strikethroughColor" json:"strikethroughColor,omitempty"`
	UnderlineStyle     UnderlineStyle     `protobuf:"varint,8,opt,name=underlineStyle,enum=text.UnderlineStyle" json:"underlineStyle,omitempty"`
	UnderlineColor     *Color             `protobuf:"bytes,10,opt,name=underlineColor" json:"underlineColor,omitempty"`
	Font               *Font              `protobuf:"bytes,12,opt,name=font" json:"font,omitempty"`
	Hyphenation        float64            `protobuf:"fixed64,14,opt,name=hyphenation" json:"hyphenation,omitempty"`
	LineHeightMultiple float64            `protobuf:"fixed64,16,opt,name=lineHeightMultiple" json:"lineHeightMultiple,omitempty"`
	MaxLines           int64              `protobuf:"varint,18,opt,name=maxLines" json:"maxLines,omitempty"`
	TextColor          *Color             `protobuf:"bytes,20,opt,name=textColor" json:"textColor,omitempty"`
	Wrap               TextWrap           `protobuf:"varint,22,opt,name=wrap,enum=text.TextWrap" json:"wrap,omitempty"`
	Truncation         Truncation         `protobuf:"varint,24,opt,name=truncation,enum=text.Truncation" json:"truncation,omitempty"`
	TruncationString   string             `protobuf:"bytes,26,opt,name=truncationString" json:"truncationString,omitempty"`
}

func (m *TextStyle) Reset()                    { *m = TextStyle{} }
func (m *TextStyle) String() string            { return proto.CompactTextString(m) }
func (*TextStyle) ProtoMessage()               {}
func (*TextStyle) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{4} }

func (m *TextStyle) GetTextAlignment() TextAlignment {
	if m != nil {
		return m.TextAlignment
	}
	return TextAlignment_TEXT_ALIGNMENT_LEFT
}

func (m *TextStyle) GetStrikethroughStyle() StrikethroughStyle {
	if m != nil {
		return m.StrikethroughStyle
	}
	return StrikethroughStyle_STRIKETHROUGH_STYLE_NONE
}

func (m *TextStyle) GetStrikethroughColor() *Color {
	if m != nil {
		return m.StrikethroughColor
	}
	return nil
}

func (m *TextStyle) GetUnderlineStyle() UnderlineStyle {
	if m != nil {
		return m.UnderlineStyle
	}
	return UnderlineStyle_UNDRELINE_STYLE_NONE
}

func (m *TextStyle) GetUnderlineColor() *Color {
	if m != nil {
		return m.UnderlineColor
	}
	return nil
}

func (m *TextStyle) GetFont() *Font {
	if m != nil {
		return m.Font
	}
	return nil
}

func (m *TextStyle) GetHyphenation() float64 {
	if m != nil {
		return m.Hyphenation
	}
	return 0
}

func (m *TextStyle) GetLineHeightMultiple() float64 {
	if m != nil {
		return m.LineHeightMultiple
	}
	return 0
}

func (m *TextStyle) GetMaxLines() int64 {
	if m != nil {
		return m.MaxLines
	}
	return 0
}

func (m *TextStyle) GetTextColor() *Color {
	if m != nil {
		return m.TextColor
	}
	return nil
}

func (m *TextStyle) GetWrap() TextWrap {
	if m != nil {
		return m.Wrap
	}
	return TextWrap_TEXT_WRAP_NONE
}

func (m *TextStyle) GetTruncation() Truncation {
	if m != nil {
		return m.Truncation
	}
	return Truncation_TRUNCATION_NONE
}

func (m *TextStyle) GetTruncationString() string {
	if m != nil {
		return m.TruncationString
	}
	return ""
}

func init() {
	proto.RegisterType((*SizeFunc)(nil), "text.SizeFunc")
	proto.RegisterType((*Text)(nil), "text.Text")
	proto.RegisterType((*Font)(nil), "text.Font")
	proto.RegisterType((*Color)(nil), "text.Color")
	proto.RegisterType((*TextStyle)(nil), "text.TextStyle")
	proto.RegisterEnum("text.TextAlignment", TextAlignment_name, TextAlignment_value)
	proto.RegisterEnum("text.StrikethroughStyle", StrikethroughStyle_name, StrikethroughStyle_value)
	proto.RegisterEnum("text.UnderlineStyle", UnderlineStyle_name, UnderlineStyle_value)
	proto.RegisterEnum("text.TextWrap", TextWrap_name, TextWrap_value)
	proto.RegisterEnum("text.Truncation", Truncation_name, Truncation_value)
}

func init() { proto.RegisterFile("github.com/overcyn/mochi/pb/text.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 812 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x55, 0x4d, 0x6f, 0xeb, 0x44,
	0x14, 0x7d, 0x4e, 0xd2, 0xbe, 0xf6, 0x96, 0xe4, 0x0d, 0xb7, 0x69, 0x71, 0x23, 0x78, 0xaa, 0x22,
	0x01, 0x25, 0x8b, 0x14, 0xf5, 0xad, 0x10, 0x6c, 0xdc, 0x78, 0xd2, 0x98, 0xa6, 0x4e, 0x35, 0x9e,
	0xa8, 0x3c, 0x36, 0x95, 0x93, 0x4e, 0x13, 0x0b, 0x67, 0x1c, 0xb9, 0x0e, 0x24, 0xc0, 0xaf, 0xe1,
	0x3f, 0xf0, 0x43, 0xf8, 0x3d, 0x6c, 0xd0, 0x8c, 0xf3, 0x1d, 0x97, 0xdd, 0xcc, 0x39, 0xe7, 0x9e,
	0x7b, 0xae, 0xe7, 0x4a, 0x86, 0xaf, 0x06, 0x41, 0x32, 0x9c, 0xf4, 0xea, 0xfd, 0x68, 0x74, 0x19,
	0xfd, 0x2a, 0xe2, 0xfe, 0x4c, 0x5e, 0x8e, 0xa2, 0xfe, 0x30, 0xb8, 0x1c, 0xf7, 0x2e, 0x13, 0x31,
	0x4d, 0xea, 0xe3, 0x38, 0x4a, 0x22, 0x2c, 0xa8, 0x73, 0xe5, 0xe2, 0xff, 0xd4, 0xa1, 0x3f, 0x8b,
	0x26, 0x73, 0x7d, 0xf5, 0x4f, 0x38, 0xf0, 0x82, 0xdf, 0x45, 0x73, 0x22, 0xfb, 0xf8, 0x1e, 0x74,
	0xb5, 0x69, 0x9c, 0x1b, 0x17, 0x47, 0x57, 0x50, 0xd7, 0xb6, 0x5c, 0x4c, 0x13, 0xa6, 0x71, 0xfc,
	0x1a, 0xde, 0x8e, 0x02, 0xa9, 0xe4, 0x66, 0x4e, 0x4b, 0x8a, 0xf5, 0xb9, 0xd7, 0x7d, 0x14, 0xc8,
	0x84, 0x2d, 0x58, 0x2d, 0xf4, 0xa7, 0x5a, 0x98, 0xcf, 0x16, 0xa6, 0x6c, 0xd5, 0x82, 0x82, 0xf2,
	0xc7, 0x2f, 0x61, 0xef, 0x25, 0x99, 0x85, 0x62, 0xde, 0xfa, 0xdd, 0xaa, 0xb5, 0xa7, 0x60, 0x96,
	0xb2, 0x88, 0xf3, 0x80, 0xaa, 0xfb, 0x61, 0x1a, 0xaa, 0xda, 0x84, 0x42, 0x33, 0x92, 0x09, 0x9e,
	0xc2, 0xfe, 0xb3, 0x3f, 0x0a, 0xc2, 0x99, 0xf6, 0x38, 0x64, 0xf3, 0x9b, 0xaa, 0x79, 0xf6, 0xfb,
	0x62, 0x51, 0xa3, 0xce, 0x0a, 0x7b, 0x59, 0x84, 0x33, 0x98, 0x3e, 0x57, 0x3f, 0xc2, 0x5e, 0x23,
	0x0a, 0xa3, 0x18, 0x09, 0xe4, 0x63, 0xf1, 0xa4, 0x5d, 0x8a, 0x4c, 0x1d, 0x95, 0xbc, 0x17, 0x4e,
	0x52, 0x8b, 0x22, 0xd3, 0x67, 0x2c, 0xc3, 0xde, 0x20, 0x16, 0x42, 0x6a, 0x8f, 0x22, 0x4b, 0x2f,
	0x0a, 0xf5, 0xc3, 0xf1, 0xd0, 0x37, 0x0b, 0x29, 0xaa, 0x2f, 0xd5, 0x7f, 0x0b, 0x70, 0xb8, 0x9c,
	0x05, 0xbf, 0x83, 0xa2, 0x0a, 0x6e, 0x85, 0xc1, 0x40, 0x8e, 0x84, 0x4c, 0xa7, 0x29, 0x5d, 0x1d,
	0xaf, 0x66, 0x5e, 0x52, 0x6c, 0x53, 0x89, 0x2d, 0xc0, 0x97, 0x24, 0x0e, 0x7e, 0x11, 0xc9, 0x30,
	0x8e, 0x26, 0x83, 0xa1, 0x36, 0xd4, 0xbd, 0x4a, 0x57, 0x66, 0x5a, 0xef, 0xed, 0xf0, 0x2c, 0xa3,
	0x06, 0xbf, 0xdf, 0x72, 0xd2, 0xa3, 0x9b, 0xfb, 0xfa, 0xeb, 0x1f, 0xa5, 0x4e, 0x1a, 0x62, 0x19,
	0x32, 0xfc, 0x01, 0x4a, 0x13, 0xf9, 0x24, 0xe2, 0x30, 0x90, 0x22, 0x8d, 0x70, 0xa0, 0x23, 0x94,
	0xd3, 0xc2, 0xee, 0x06, 0xc7, 0xb6, 0xb4, 0xf8, 0x61, 0xad, 0x3a, 0x6d, 0x0b, 0xbb, 0x6d, 0xb7,
	0x24, 0x6a, 0x35, 0x9f, 0x23, 0x99, 0x98, 0x9f, 0xac, 0xaf, 0xa6, 0x7a, 0x77, 0xa6, 0x71, 0x3c,
	0x87, 0xa3, 0xe1, 0x6c, 0x3c, 0x14, 0xd2, 0x4f, 0x82, 0x48, 0x9a, 0x25, 0xfd, 0xb0, 0xeb, 0x10,
	0xd6, 0x01, 0x95, 0x5d, 0x4b, 0x04, 0x83, 0x61, 0x72, 0x37, 0x09, 0x93, 0x60, 0x1c, 0x0a, 0x93,
	0x68, 0x61, 0x06, 0x83, 0x15, 0x38, 0x18, 0xf9, 0xd3, 0x76, 0x20, 0xc5, 0x8b, 0x89, 0xe7, 0xc6,
	0x45, 0x9e, 0x2d, 0xef, 0xf8, 0x0d, 0x1c, 0xaa, 0x00, 0x69, 0xfa, 0xf2, 0x6e, 0xfa, 0x15, 0x8b,
	0x55, 0x28, 0xfc, 0x16, 0xfb, 0x63, 0xf3, 0x54, 0x7f, 0xa1, 0xd2, 0xea, 0x91, 0x1f, 0x62, 0x7f,
	0xcc, 0x34, 0x87, 0xdf, 0x02, 0x24, 0xf1, 0x44, 0xf6, 0xd3, 0xec, 0xa6, 0x56, 0x92, 0xb9, 0x72,
	0x89, 0xb3, 0x35, 0x0d, 0xd6, 0x80, 0xac, 0x6e, 0xea, 0xc9, 0xe5, 0xc0, 0xac, 0xe8, 0x05, 0xdf,
	0xc1, 0x6b, 0x7f, 0x40, 0x71, 0x63, 0xa9, 0xf0, 0x33, 0x38, 0xe6, 0xf4, 0x27, 0xfe, 0x68, 0xb5,
	0x9d, 0x1b, 0xf7, 0x8e, 0xba, 0xfc, 0xb1, 0x4d, 0x9b, 0x9c, 0xbc, 0x41, 0x13, 0xca, 0x5b, 0x04,
	0x73, 0x6e, 0x5a, 0x9c, 0x18, 0x78, 0x06, 0x27, 0x5b, 0x4c, 0x83, 0xba, 0x9c, 0x32, 0x92, 0xc3,
	0xcf, 0xc1, 0xdc, 0xa2, 0x7e, 0xec, 0x7a, 0xdc, 0x69, 0x3a, 0xd4, 0x26, 0xf9, 0xda, 0x3f, 0x06,
	0xe0, 0xee, 0x4a, 0xaa, 0x22, 0x8f, 0x33, 0xe7, 0x96, 0xf2, 0x16, 0xeb, 0x74, 0x6f, 0x5a, 0x8f,
	0x1e, 0xff, 0xd8, 0xa6, 0x8f, 0x6e, 0xc7, 0xa5, 0xe4, 0x0d, 0xbe, 0x87, 0x4a, 0x16, 0xeb, 0x39,
	0xee, 0x4d, 0x9b, 0x12, 0xe3, 0x35, 0xde, 0xee, 0x74, 0xaf, 0xdb, 0x94, 0xe4, 0xf0, 0x0b, 0x38,
	0xcb, 0xe2, 0x79, 0xcb, 0x69, 0xdc, 0x92, 0xfc, 0xeb, 0xe5, 0x9c, 0x53, 0x9b, 0x14, 0x5e, 0xe5,
	0x2d, 0xaf, 0x45, 0x6d, 0xb2, 0x57, 0xfb, 0xdb, 0x80, 0xd2, 0xe6, 0x8e, 0xab, 0x2f, 0xd7, 0x75,
	0x6d, 0x46, 0xdb, 0x8e, 0x4b, 0x37, 0x67, 0xa9, 0xc0, 0xe9, 0x36, 0xb3, 0x9c, 0x23, 0x83, 0x5b,
	0xce, 0x70, 0x06, 0x27, 0xdb, 0xdc, 0x22, 0x7f, 0x66, 0xd9, 0x3c, 0x7b, 0x16, 0xb7, 0xc8, 0x7d,
	0x0b, 0x07, 0x8b, 0xc5, 0x43, 0x84, 0x92, 0x7e, 0xb5, 0x07, 0x66, 0xdd, 0x2f, 0xa2, 0x6e, 0x60,
	0x0f, 0x1d, 0x66, 0x13, 0x63, 0xb9, 0x2b, 0x1a, 0x6b, 0xb4, 0x2c, 0x66, 0x35, 0xf4, 0xb3, 0xd7,
	0x7a, 0x00, 0xab, 0xdd, 0xc4, 0x63, 0x78, 0xc7, 0x59, 0xd7, 0x6d, 0x58, 0xdc, 0xe9, 0xb8, 0x0b,
	0xbf, 0x32, 0x90, 0x35, 0xd0, 0xe3, 0x16, 0x53, 0xab, 0x74, 0x02, 0x9f, 0xae, 0xa1, 0x77, 0x8e,
	0x6d, 0xeb, 0x79, 0x55, 0xf3, 0x15, 0x4c, 0x5d, 0x9b, 0xe4, 0xaf, 0x4b, 0x3f, 0xe7, 0xc6, 0xbd,
	0xbf, 0x72, 0x6f, 0xef, 0xd4, 0x9f, 0xeb, 0xfe, 0xba, 0xb7, 0xaf, 0x7f, 0x59, 0x1f, 0xfe, 0x0b,
	0x00, 0x00, 0xff, 0xff, 0x13, 0xfa, 0x11, 0x27, 0x0c, 0x07, 0x00, 0x00,
}
