// Code generated by protoc-gen-go. DO NOT EDIT.
// source: touch.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RecognizerList struct {
	Recognizers     []*google_protobuf.Any `protobuf:"bytes,1,rep,name=recognizers" json:"recognizers,omitempty"`
	RecognizerNames []string               `protobuf:"bytes,2,rep,name=recognizerNames" json:"recognizerNames,omitempty"`
}

func (m *RecognizerList) Reset()                    { *m = RecognizerList{} }
func (m *RecognizerList) String() string            { return proto.CompactTextString(m) }
func (*RecognizerList) ProtoMessage()               {}
func (*RecognizerList) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{0} }

func (m *RecognizerList) GetRecognizers() []*google_protobuf.Any {
	if m != nil {
		return m.Recognizers
	}
	return nil
}

func (m *RecognizerList) GetRecognizerNames() []string {
	if m != nil {
		return m.RecognizerNames
	}
	return nil
}

type TapRecognizer struct {
	Count int64 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
}

func (m *TapRecognizer) Reset()                    { *m = TapRecognizer{} }
func (m *TapRecognizer) String() string            { return proto.CompactTextString(m) }
func (*TapRecognizer) ProtoMessage()               {}
func (*TapRecognizer) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{1} }

func (m *TapRecognizer) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type PressRecognizer struct {
}

func (m *PressRecognizer) Reset()                    { *m = PressRecognizer{} }
func (m *PressRecognizer) String() string            { return proto.CompactTextString(m) }
func (*PressRecognizer) ProtoMessage()               {}
func (*PressRecognizer) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{2} }

type PanRecognizer struct {
}

func (m *PanRecognizer) Reset()                    { *m = PanRecognizer{} }
func (m *PanRecognizer) String() string            { return proto.CompactTextString(m) }
func (*PanRecognizer) ProtoMessage()               {}
func (*PanRecognizer) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{3} }

func init() {
	proto.RegisterType((*RecognizerList)(nil), "touch.RecognizerList")
	proto.RegisterType((*TapRecognizer)(nil), "touch.TapRecognizer")
	proto.RegisterType((*PressRecognizer)(nil), "touch.PressRecognizer")
	proto.RegisterType((*PanRecognizer)(nil), "touch.PanRecognizer")
}

func init() { proto.RegisterFile("touch.proto", fileDescriptor7) }

var fileDescriptor7 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xc9, 0x2f, 0x4d,
	0xce, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0xa4, 0x24, 0xd3, 0xf3, 0xf3,
	0xd3, 0x73, 0x52, 0xf5, 0xc1, 0x82, 0x49, 0xa5, 0x69, 0xfa, 0x89, 0x79, 0x95, 0x10, 0x15, 0x4a,
	0x45, 0x5c, 0x7c, 0x41, 0xa9, 0xc9, 0xf9, 0xe9, 0x79, 0x99, 0x55, 0xa9, 0x45, 0x3e, 0x99, 0xc5,
	0x25, 0x42, 0x66, 0x5c, 0xdc, 0x45, 0x70, 0x91, 0x62, 0x09, 0x46, 0x05, 0x66, 0x0d, 0x6e, 0x23,
	0x11, 0x3d, 0x88, 0x11, 0x7a, 0x30, 0x23, 0xf4, 0x1c, 0xf3, 0x2a, 0x83, 0x90, 0x15, 0x0a, 0x69,
	0x70, 0xf1, 0x23, 0xb8, 0x7e, 0x89, 0xb9, 0xa9, 0xc5, 0x12, 0x4c, 0x0a, 0xcc, 0x1a, 0x9c, 0x41,
	0xe8, 0xc2, 0x4a, 0xaa, 0x5c, 0xbc, 0x21, 0x89, 0x05, 0x08, 0x6b, 0x85, 0x44, 0xb8, 0x58, 0x93,
	0xf3, 0x4b, 0xf3, 0x4a, 0x24, 0x18, 0x15, 0x18, 0x35, 0x98, 0x83, 0x20, 0x1c, 0x25, 0x41, 0x2e,
	0xfe, 0x80, 0xa2, 0xd4, 0xe2, 0x62, 0x84, 0x42, 0x25, 0x7e, 0x2e, 0xde, 0x80, 0xc4, 0x3c, 0x84,
	0x80, 0x13, 0x5f, 0x14, 0x53, 0x41, 0xd2, 0x22, 0x26, 0x76, 0xdf, 0xfc, 0xe4, 0x8c, 0xcc, 0x00,
	0xa7, 0x24, 0x36, 0xb0, 0xfb, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xac, 0xa4, 0xfd, 0x02,
	0x06, 0x01, 0x00, 0x00,
}
