
// Objective-C API for talking to the following Go packages
//
//	github.com/overcyn/mochi/reverse
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Goreverse_FRAMEWORK_H__
#define __Goreverse_FRAMEWORK_H__

#include "Goreverse.objc.h"
#include "Universe.objc.h"

#endif
