// Objective-C API for talking to github.com/overcyn/mochi/reverse Go package.
//   gobind -lang=objc github.com/overcyn/mochi/reverse
//
// File is generated by gobind. Do not edit.

#ifndef __Goreverse_H__
#define __Goreverse_H__

@import Foundation;
#include "Universe.objc.h"


FOUNDATION_EXPORT NSString* GoreverseGetDate();

#endif
